[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NEXT_PUBLIC_SUPABASE_URL = "https://dppvroecyfwmidtjxxup.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwcHZyb2VjeWZ3bWlkdGp4eHVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0OTk2ODUsImV4cCI6MjA3NDA3NTY4NX0.W8VjlBZkfKR-whUYqn3YiDTE-MgQEmKk7HlHI1vQowg"
  NEXT_PUBLIC_APP_URL = "https://geumnikkaebi.netlify.app"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next"
  status = 200